### ISSUE TITLE
How to set the conf data?

### ISSUE THREAD

**Issue by Ramblurr** [glerchundi/kubernetes-http-loadbalancer#1]
I setup the three pods included in the example. From my master server I manually set the `/lb/hosts` keys using `etcdctl set ...`

But how are the  `/lb/upstreams/helloworld-` keys supposed to be set? What are the subkeys under `/servers`  (in the example they are guids, referring to what?)

**Comment by glerchundi** [comment]
hi @Ramblurr, you can set it manually but the idea of this pod is to automatically set upstreams/servers through [loadbalancer-feeder](https://github.com/just-containers/loadbalancer-feeder). Take a look to this file which is where the magic happens: [run script](https://github.com/just-containers/loadbalancer-feeder/blob/master/rootfs/etc/services.d/feeder/run)

**Comment by Ramblurr** [comment]
thanks @glerchundi I still have a few questions..
1. The `/lb/hosts` is set manually correct? (`/lb/hosts/lisa.contoso.com/...` in your README)
   Should this be set before starting the helloworld pod?
2. The conf should be written to the etcd running on the kubnernets master correct?

**Comment by glerchundi** [comment]
> The /lb/hosts is set manually correct? (/lb/hosts/lisa.contoso.com/... in your README) Should this be set before starting the helloworld pod?

Yes, they must be set manually.

> The conf should be written to the etcd running on the kubnernets master correct?

That's correct for this pod. Because I'm creating an etcd container in proxy mode which forward everything to the master etcd but this is just an example and you can change it to fit your needs.
